module.exports = {
  apps: [
    {
      name: "ktown-backend",
      script: "server.js",
      cwd: "/root/ktown/ktown_webapp",
      interpreter: "node",
      interpreter_args: "--max-old-space-size=8192",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "2G",
      error_file: "/root/.pm2/logs/ktown-backend-error.log",
      out_file: "/root/.pm2/logs/ktown-backend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 4000,
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
    {
      name: "ktown-frontend",
      script: "npm",
      args: "start",
      cwd: "/root/ktown/ktown_webapp/client",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "/root/.pm2/logs/ktown-frontend-error.log",
      out_file: "/root/.pm2/logs/ktown-frontend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 4000,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        BROWSER: "none",
      },
      kill_timeout: 5000,
      listen_timeout: 30000, // React takes longer to start
    },
  ],
};

